[build]
target = "x86_64-bootloader.json"

[unstable]
build-std = ["core", "compiler_builtins"]

[target.x86_64-bootloader.json]
runner = "qemu-system-x86_64 -drive format=raw,file=target/x86_64-bootloader/debug/x64_bootloader"
